/*
 * ConsoleWindow.java
 *
 * Created on den 8 september 2001, 00:47
 */

package xella.demo.commandline;

/**
 *
 * @author  jimmy
 */
public class ConsoleWindow extends javax.swing.JFrame {

    /** Creates new form ConsoleWindow */
    public ConsoleWindow() {
        this.getContentPane().add(new xella.swing.Console());
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        addWindowListener(new java.awt.event.WindowAdapter() {
                              public void windowClosing(java.awt.event.WindowEvent evt) {
                                  exitForm(evt);
                              }
                          }
                         );
        pack();
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new ConsoleWindow().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
